const products=[
 {id:1,n:'Sofá Retrátil 3 Lugares Reclinável',cat:'Sala',price:1899,old:2499,discount:24,img:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',best:1},
 {id:2,n:'Guarda-Roupa 6 Portas com Espelho',cat:'Quarto',price:1199,old:1499,discount:20,img:'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=800&q=80'},
 {id:3,n:'Mesa de Jantar 6 Lugares com Cadeiras',cat:'Sala de jantar',price:1069,old:1299,discount:18,img:'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=800&q=80',best:1},
 {id:4,n:'Cama Box Casal com Colchão',cat:'Quarto',price:1249,old:1599,discount:22,img:'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80'},
 {id:5,n:'Painel para TV até 65” com Nichos',cat:'Sala',price:709,old:899,discount:21,img:'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80',best:1},
 {id:6,n:'Rack para TV 2 Portas',cat:'Sala',price:579,old:749,discount:23,img:'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?auto=format&fit=crop&w=800&q=80'},
 {id:7,n:'Cômoda 4 Gavetas Nature',cat:'Quarto',price:449,old:599,discount:25,img:'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80'},
 {id:8,n:'Colchão Casal D33',cat:'Colchões',price:699,old:899,discount:22,img:'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80'},
 {id:9,n:'Armário de Cozinha 8 Portas',cat:'Cozinha',price:899,old:1199,discount:25,img:'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=800&q=80'},
 {id:10,n:'Poltrona Decorativa Oslo',cat:'Sala',price:399,old:529,discount:24,img:'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=800&q=80'},
 {id:11,n:'Escrivaninha Compacta Office',cat:'Escritório',price:329,old:449,discount:27,img:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=800&q=80'},
 {id:12,n:'Geladeira Frost Free 375L',cat:'Eletrodomésticos',price:2899,old:3299,discount:12,img:'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80'},
 {id:13,n:'Buffet Aparador 4 Portas Freijó',cat:'Sala de jantar',price:799,old:1099,discount:27,img:'https://images.unsplash.com/photo-1713810958247-01dbd76b4a61?auto=format&fit=crop&w=800&q=80',best:1,badge:'Novidade',description:'Design contemporâneo com amplo espaço interno e acabamento amadeirado.',rating:4.8,reviews:74,installmentCount:10,installmentValue:79.90},
 {id:14,n:'Estante Livreiro 5 Nichos Industrial',cat:'Organização',price:429,old:599,discount:28,img:'https://images.unsplash.com/photo-1718524767499-7fe3a6ab4f8c?auto=format&fit=crop&w=800&q=80',badge:'Oferta',description:'Estrutura versátil para livros, plantas e objetos decorativos.',rating:4.7,reviews:53,installmentCount:10,installmentValue:42.90},
 {id:15,n:'Mesa de Centro Elevatória com Baú',cat:'Sala',price:459,old:649,discount:29,img:'https://images.unsplash.com/photo-1618220048045-10a6dbdf83e0?auto=format&fit=crop&w=800&q=80',best:1,badge:'Mais vendido',description:'Tampo elevatório e compartimento interno para uma sala mais organizada.',rating:4.9,reviews:126,installmentCount:10,installmentValue:45.90},
 {id:16,n:'Beliche Juvenil com Escada e Gavetas',cat:'Quarto',price:1299,old:1699,discount:24,img:'https://images.unsplash.com/photo-1721743169043-dda0212ce3d4?auto=format&fit=crop&w=800&q=80',badge:'Novidade',description:'Solução compacta com proteção lateral e gavetas para otimizar o quarto.',rating:4.8,reviews:61,installmentCount:10,installmentValue:129.90},
 {id:17,n:'Cama Infantil com Grade de Proteção',cat:'Quarto',price:749,old:999,discount:25,img:'https://images.unsplash.com/photo-1723258343563-7d71a55d6dfa?auto=format&fit=crop&w=800&q=80',description:'Modelo acolhedor com acesso baixo e proteção para noites tranquilas.',rating:4.9,reviews:89,installmentCount:10,installmentValue:74.90},
 {id:18,n:'Lavadora Automática 12kg Inverter',cat:'Eletrodomésticos',price:2199,old:2599,discount:15,img:'https://images.unsplash.com/photo-1626806819282-2c1dc01a5e0c?auto=format&fit=crop&w=800&q=80',best:1,badge:'Destaque',description:'Alta capacidade, ciclos inteligentes e funcionamento econômico.',rating:4.8,reviews:142,installmentCount:10,installmentValue:219.90},
 {id:19,n:'Lava e Seca 11kg Premium',cat:'Eletrodomésticos',price:3199,old:3799,discount:16,img:'https://images.unsplash.com/photo-1657064575960-efefbe831c2e?auto=format&fit=crop&w=800&q=80',badge:'Oferta',description:'Lavagem e secagem no mesmo ciclo com painel digital intuitivo.',rating:4.9,reviews:97,installmentCount:10,installmentValue:319.90},
 {id:20,n:'Armário Multiuso 2 Portas Nature',cat:'Organização',price:549,old:749,discount:27,img:'https://images.unsplash.com/photo-1628152371231-936cf45eb8f3?auto=format&fit=crop&w=800&q=80',description:'Prateleiras internas reguláveis para organizar diferentes ambientes.',rating:4.7,reviews:48,installmentCount:10,installmentValue:54.90},
 {id:21,n:'Cadeira Office Ergonômica Giratória',cat:'Escritório',price:699,old:899,discount:22,img:'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&w=800&q=80',badge:'Conforto',description:'Encosto ergonômico, regulagem de altura e rodízios para uma rotina mais confortável.',rating:4.9,reviews:118,installmentCount:10,installmentValue:69.90},
 {id:22,n:'Mesa Office Industrial com 2 Gavetas',cat:'Escritório',price:549,old:749,discount:27,img:'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80',badge:'Novidade',description:'Tampo amplo e gavetas funcionais para organizar estudos e trabalho.',rating:4.8,reviews:67,installmentCount:10,installmentValue:54.90},
 {id:23,n:'Armário de Escritório Alto 2 Portas',cat:'Escritório',price:629,old:849,discount:26,img:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=800&q=80',badge:'Organização',description:'Espaço interno versátil para documentos, materiais e objetos de uso diário.',rating:4.7,reviews:44,installmentCount:10,installmentValue:62.90},
 {id:24,n:'Gaveteiro Office 3 Gavetas com Rodízios',cat:'Escritório',price:389,old:519,discount:25,img:'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',badge:'Praticidade',description:'Organização compacta para documentos e materiais, com mobilidade para o dia a dia.',rating:4.8,reviews:39,installmentCount:10,installmentValue:38.90},
 {id:25,n:'Estante Office 5 Prateleiras',cat:'Escritório',price:479,old:649,discount:26,img:'https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=800&q=80',badge:'Versátil',description:'Estrutura vertical para livros, pastas e decoração sem ocupar muito espaço.',rating:4.7,reviews:52,installmentCount:10,installmentValue:47.90},
 {id:26,n:'Mesa em L para Escritório Compacto',cat:'Escritório',price:829,old:1099,discount:25,img:'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&q=80',badge:'Mais espaço',description:'Formato em L com área ampla para computador, estudos e organização da rotina.',rating:4.9,reviews:83,installmentCount:10,installmentValue:82.90},
 {id:27,n:'Cadeira Presidente Reclinável',cat:'Escritório',price:899,old:1199,discount:25,img:'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80',badge:'Premium',description:'Assento acolchoado, braços de apoio e ajuste para longas jornadas com conforto.',rating:4.9,reviews:105,installmentCount:10,installmentValue:89.90}];
const cats=[['Sala','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=300&q=70'],['Quarto','https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=300&q=70'],['Cozinha','https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=300&q=70'],['Sala de jantar','https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=300&q=70'],['Escritório','https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=300&q=70'],['Colchões','https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=300&q=70'],['Eletrodomésticos','https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=300&q=70'],['Organização','https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=300&q=70']];
let cart=JSON.parse(localStorage.getItem('movel-cart')||'[]'), favs=JSON.parse(localStorage.getItem('movel-favs')||'[]'), activeCat='Todas', offersOnly=false;
const brl=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const storeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[char]);
const commerceSettings={whatsapp:'',message:'Olá! 👋',buttonText:'COMPRAR PELO WHATSAPP',buttonSubtitle:'Fale com a loja e garanta este produto agora!',secureBenefit:'Compra segura',pickupBenefit:'Retire na loja',serviceRegion:'Atendimento na cidade'};
function storeIcon(name){const icons={whatsapp:'<path d="M20.5 11.6a8.5 8.5 0 0 1-12.6 7.5L3 20.5l1.4-4.7A8.5 8.5 0 1 1 20.5 11.6Z"/><path d="M8.2 7.5c.3-.5.6-.5 1-.5h.5c.2 0 .4.1.5.4l.8 2c.1.3.1.5-.1.7l-.6.8c-.2.2-.2.4-.1.6.6 1.2 1.6 2.2 2.8 2.8.2.1.4.1.6-.1l.8-1c.2-.2.4-.3.7-.2l2 .9c.3.1.4.3.4.5 0 .4-.2 1.3-.7 1.8-.5.6-1.5.9-2.4.7-1.3-.2-3.1-.9-5-2.6-1.5-1.4-2.5-3.2-2.8-4.5-.3-1.1 0-1.8.4-2.3Z"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"/>',bag:'<path d="M6 8h12l1 13H5L6 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/>',truck:'<path d="M3 6h11v10H3zM14 10h4l3 3v3h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="17" cy="18" r="2"/>',tools:'<path d="m14.5 6.5 3-3a4 4 0 0 1-5 5l-7 7a2 2 0 1 1-3-3l7-7a4 4 0 0 1 5-5l-3 3 3 3Z"/><path d="m14 14 6 6"/>',shield:'<path d="M12 3 5 6v5c0 4.7 2.9 8.1 7 10 4.1-1.9 7-5.3 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/>',store:'<path d="M4 10v10h16V10M3 10l2-6h14l2 6"/><path d="M8 20v-6h5v6M3 10c0 2 3 2 3 0 0 2 3 2 3 0 0 2 3 2 3 0 0 2 3 2 3 0 0 2 3 2 3 0"/>',pin:'<path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',arrow:'<path d="m9 18 6-6-6-6"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||''}</svg>`}
function applyStorefrontCommerceSettings(settings={}){commerceSettings.whatsapp=String(settings.whatsapp||'').replace(/\D/g,'');commerceSettings.message=String(settings.whatsapp_message||commerceSettings.message).trim();commerceSettings.buttonText=String(settings.whatsapp_button_text||commerceSettings.buttonText).trim();commerceSettings.buttonSubtitle=String(settings.whatsapp_button_subtitle||commerceSettings.buttonSubtitle).trim();commerceSettings.secureBenefit=String(settings.product_benefit_secure_text||commerceSettings.secureBenefit).trim();commerceSettings.pickupBenefit=String(settings.product_benefit_pickup_text||commerceSettings.pickupBenefit).trim();const region=String(settings.service_region||[settings.city,settings.state].filter(Boolean).join(' - ')||'').trim();commerceSettings.serviceRegion=region?`Atendimento em ${region}`:'Atendimento na cidade';render()}
window.setStorefrontCommerceSettings=applyStorefrontCommerceSettings;
function productCode(p){return p.sku||`MOV-${String(p.id).padStart(4,'0')}`}
function productUrl(p){const url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('product',p.dbId||p.id);return url.href}
function openWhatsAppMessage(message){if(!commerceSettings.whatsapp){toast('WhatsApp da loja ainda não foi configurado.');return}window.open(`https://wa.me/${commerceSettings.whatsapp}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')}
function buyProductWhatsApp(id){const p=products.find(item=>item.id===id);if(!p||p.whatsappEnabled===false)return;openWhatsAppMessage(`${commerceSettings.message}\n\nVi este produto no site e tenho interesse em comprá-lo:\n\n${p.n}\nCódigo: ${productCode(p)}\nPreço: ${brl(p.price)}\nQuantidade: 1\n\n${productUrl(p)}\n\nGostaria de saber se está disponível e como posso finalizar a compra.`)}
function buyCartWhatsApp(){const items=cart.map(item=>({item,product:products.find(product=>product.id===item.id)})).filter(entry=>entry.product);if(!items.length)return toast('Sua sacola está vazia.');const total=items.reduce((sum,{item,product})=>sum+item.qty*product.price,0);const lines=items.map(({item,product})=>`${item.qty}x ${product.n}\nCódigo: ${productCode(product)}\n${brl(product.price)}`).join('\n\n');openWhatsAppMessage(`${commerceSettings.message}\n\nMontei uma sacola no site e tenho interesse nestes produtos:\n\n${lines}\n\nTotal dos produtos: ${brl(total)}\n\nGostaria de verificar disponibilidade e finalizar minha compra.`)}
  function officialProductCard(p){const campaign=p.campaign===true||p.badge==='Campanha';const oldPrice=p.old&&p.old>p.price?`<span class="official-product-old">${brl(p.old)}</span>`:'';const description=p.description?`<p class="official-product-description">${storeHtml(p.description)}</p>`:'';const installments=Number.isFinite(p.installmentCount)&&Number.isFinite(p.installmentValue)?`<b>ou ${p.installmentCount}x de ${brl(p.installmentValue)}</b>`:'';const photoBenefits=[p.freeCityShipping?'<span class="photo-benefit is-shipping"><img src="assets/seal-free-shipping.png" alt="Frete grátis para a cidade"></span>':'',p.freeAssembly?'<span class="photo-benefit is-assembly"><img src="assets/seal-free-assembly.png" alt="Armação gratuita"></span>':''].join('');const whatsapp=p.whatsappEnabled!==false?`<button class="product-whatsapp" type="button" onclick="buyProductWhatsApp(${p.id})">${storeIcon('whatsapp')}<span><b>${storeHtml(commerceSettings.buttonText)}</b><small>${storeHtml(commerceSettings.buttonSubtitle)}</small></span>${storeIcon('arrow')}</button>`:'';const bag=p.cartEnabled!==false?`<button class="product-add-bag" type="button" onclick="addCart(${p.id})">${storeIcon('bag')}<span>Adicionar à sacola</span></button>`:'';return `<article class="official-product-card catalog-card product-card" data-product-id="${p.id}" tabindex="0" aria-label="Ver detalhes de ${storeHtml(p.n)}"><div class="official-product-photo"><img src="${storeHtml(p.img)}" alt="${storeHtml(p.n)}" loading="lazy" width="800" height="580">${campaign?'<span class="campaign-badge">Campanha</span>':''}<button class="official-product-heart ${favs.includes(p.id)?'active':''}" type="button" onclick="toggleFav(${p.id})" aria-label="${favs.includes(p.id)?'Remover dos':'Adicionar aos'} favoritos">${storeIcon('heart')}</button>${photoBenefits?`<div class="photo-benefits">${photoBenefits}</div>`:''}</div><div class="official-product-body"><small class="official-product-category">${storeHtml(p.cat)}</small><h3>${storeHtml(p.n)}</h3>${description}<div class="official-product-price">${oldPrice}<strong>${brl(p.price)}</strong><em>à vista no Pix ou cartão${installments}</em></div><div class="official-product-benefits"><span>${storeIcon('shield')}<b>${storeHtml(commerceSettings.secureBenefit)}</b></span><span>${storeIcon('store')}<b>${storeHtml(commerceSettings.pickupBenefit)}</b></span><span>${storeIcon('pin')}<b>${storeHtml(commerceSettings.serviceRegion)}</b></span></div><div class="official-product-actions">${whatsapp}${bag}</div></div></article>`}
function card(p){return officialProductCard(p)}
const environmentCats=[
 {label:'Sala de estar',category:'Sala',img:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=700&q=80'},
 {label:'Quarto',category:'Quarto',img:'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=700&q=80'},
 {label:'Cozinha e jantar',category:'Cozinha',img:'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=700&q=80'},
 {label:'Escritório',category:'Escritório',img:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=700&q=80'},
 {label:'Organização',category:'Organização',img:'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=700&q=80'},
 {label:'Eletros',category:'Eletrodomésticos',img:'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=700&q=80'},
 {label:'Sala de jantar',category:'Sala de jantar',img:'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=700&q=80'},
 {label:'Colchões',category:'Colchões',img:'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=700&q=80'}
];
function renderCats(){document.querySelector('#categoryRow').innerHTML=environmentCats.map(c=>`<button class="category" type="button" onclick="filterCategory('${c.category}')"><img src="${c.img}" alt="${c.label}" loading="lazy" width="700" height="470"><b>${c.label}</b></button>`).join('')}
function initCategoryCarousel(){const row=document.querySelector('#categoryRow');const prev=document.querySelector('.category-prev');const next=document.querySelector('.category-next');if(!row||!prev||!next)return;const amount=()=>Math.max(row.clientWidth*.82,260);prev.onclick=()=>row.scrollBy({left:-amount(),behavior:'smooth'});next.onclick=()=>row.scrollBy({left:amount(),behavior:'smooth'});let dragging=false,dragged=false,startX=0,startScroll=0;row.addEventListener('mousedown',e=>{if(e.button!==0)return;dragging=true;dragged=false;startX=e.clientX;startScroll=row.scrollLeft;row.classList.add('is-dragging')});row.addEventListener('mousemove',e=>{if(!dragging)return;const distance=e.clientX-startX;if(Math.abs(distance)>8)dragged=true;row.scrollLeft=startScroll-distance;if(dragged)e.preventDefault()});const stop=()=>{dragging=false;row.classList.remove('is-dragging')};window.addEventListener('mouseup',stop);row.addEventListener('mouseleave',stop);row.addEventListener('click',e=>{if(!dragged)return;e.preventDefault();e.stopPropagation();dragged=false},true)}
function render(){const sectionLimit=8;document.querySelector('#offerGrid').innerHTML=products.slice(0,sectionLimit).map(card).join('');const bestProducts=[...products.filter(p=>p.best),...products.filter(p=>!p.best)].slice(0,sectionLimit);document.querySelector('#bestGrid').innerHTML=bestProducts.map(card).join('');const officeGrid=document.querySelector('#officeGrid');if(officeGrid)officeGrid.innerHTML=products.filter(p=>p.cat==='Escritório').slice(0,sectionLimit).map(catalogCard).join('');renderCatalog();updateCounts()}
function clearCatalogSearch(){const field=document.querySelector('#search');if(field){field.value='';field.setAttribute('aria-expanded','false')}const suggestions=document.querySelector('#suggestions');if(suggestions)suggestions.style.display='none'}
function renderCatalog(){
 let list=products.filter(p=>activeCat==='Todas'||p.cat===activeCat);
 if(offersOnly)list=list.filter(p=>p.badge==='Oferta'||p.discount>=25);
 let q=document.querySelector('#search').value.toLowerCase();
 if(q)list=list.filter(p=>p.n.toLowerCase().includes(q)||p.cat.toLowerCase().includes(q));
 let sort=document.querySelector('#sort').value;
 if(sort==='Menor preço')list.sort((a,b)=>a.price-b.price);
 if(sort==='Maior preço')list.sort((a,b)=>b.price-a.price);
 document.querySelector('#catalogGrid').innerHTML=list.length?list.map(catalogCard).join(''):`<div class="empty">Nenhum produto encontrado.<br><a class="admin-link" href="#inicio">Voltar para a home</a></div>`;
 const singular=list.length===1;
 const noun=offersOnly?(singular?'oferta encontrada':'ofertas encontradas'):(singular?'produto encontrado':'produtos encontrados');
 document.querySelector('#resultLabel').textContent=`${list.length} ${noun}`;
 const catalogLink=document.querySelector('#catalogLink');
 if(catalogLink)catalogLink.textContent=offersOnly?`${list.length} ${singular?'oferta selecionada':'ofertas selecionadas'}`:`Ver ${singular?'':'os '}${list.length} ${singular?'produto':'produtos'} →`;
 document.querySelector('#filterPills').innerHTML=['Todas',...cats.map(c=>c[0])].map(c=>`<button class="pill ${!offersOnly&&activeCat===c?'active':''}" type="button" onclick="filterCategory('${c}')">${c}</button>`).join('');
}
function filterCategory(c){offersOnly=false;activeCat=c;clearCatalogSearch();renderCatalog();document.querySelector('#catalogo').scrollIntoView({behavior:'smooth'})}
function showOffers(){offersOnly=true;activeCat='Todas';clearCatalogSearch();renderCatalog();document.querySelector('#catalogo').scrollIntoView({behavior:'smooth'})}
function addCart(id){let p=products.find(x=>x.id===id);if(!p||p.cartEnabled===false)return toast('Este produto está disponível somente pelo WhatsApp.');let item=cart.find(x=>x.id===id);item?item.qty++:cart.push({id,qty:1});save();toast('Produto adicionado à sacola');}
function toggleFav(id){favs.includes(id)?favs=favs.filter(x=>x!==id):favs.push(id);localStorage.setItem('movel-favs',JSON.stringify(favs));render();toast(favs.includes(id)?'Adicionado aos favoritos':'Removido dos favoritos')}
function save(){localStorage.setItem('movel-cart',JSON.stringify(cart));updateCounts()};function updateCounts(){let n=cart.reduce((s,i)=>s+i.qty,0);document.querySelectorAll('#cartCount,#cartBadge,#mobileBadge').forEach(e=>e.textContent=e.id==='cartCount'?`${n} item${n!==1?'s':''}`:n);document.querySelector('#favCount').textContent=`${favs.length} item${favs.length!==1?'s':''}`}
function toast(t){let e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
let drawerReturnFocus=null,drawerHistoryPushed=false;
function openDrawer(html){const drawer=document.querySelector('#drawer');const wasOpen=drawer.classList.contains('open');if(!wasOpen)drawerReturnFocus=document.activeElement;document.querySelector('#drawerContent').innerHTML=html;drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');if(!wasOpen){history.pushState({...history.state,storeDrawer:true},'');drawerHistoryPushed=true}requestAnimationFrame(()=>drawer.querySelector('.close')?.focus())}
function closeDrawer(fromHistory=false){const drawer=document.querySelector('#drawer');if(!drawer.classList.contains('open'))return;drawer.classList.remove('open','product-detail-open');drawer.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');document.querySelector('.menu')?.setAttribute('aria-expanded','false');if(!fromHistory&&drawerHistoryPushed&&history.state?.storeDrawer){drawerHistoryPushed=false;history.back()}else drawerHistoryPushed=false;drawerReturnFocus?.focus?.();drawerReturnFocus=null}
function openCart(){const validCart=cart.filter(i=>products.some(p=>p.id===i.id));let lines=validCart.map(i=>{let p=products.find(x=>x.id===i.id);return `<div class="cart-line"><img src="${storeHtml(p.img)}" alt="${storeHtml(p.n)}" loading="lazy" width="96" height="96"><h4>${storeHtml(p.n)}<br><small>${i.qty} × ${brl(p.price)}</small></h4><b>${brl(i.qty*p.price)}</b><button type="button" onclick="removeCart(${p.id})" aria-label="Remover ${storeHtml(p.n)} da sacola">×</button></div>`}).join('');let total=validCart.reduce((s,i)=>s+i.qty*products.find(p=>p.id===i.id).price,0);openDrawer(`<h2>Sua sacola</h2>${lines||'<div class="empty">Sua sacola está vazia.<br>Que tal encontrar o móvel perfeito para sua casa?</div>'}${validCart.length?`<div class="cart-total"><span>Total dos produtos</span><span>${brl(total)}</span></div><button class="cart-whatsapp-checkout" type="button" onclick="buyCartWhatsApp()">${storeIcon('whatsapp')}<span><b>COMPRAR SACOLA PELO WHATSAPP</b><small>Enviar todos os produtos para a loja</small></span>${storeIcon('arrow')}</button>`:''}`)}
function removeCart(id){cart=cart.filter(x=>x.id!==id);save();openCart();toast('Produto removido')};function openAccount(){openDrawer('<h2>Minha conta</h2><p style="color:#66758c">Entre para acompanhar pedidos e salvar seus favoritos.</p><label class="drawer-field" for="accountEmail"><span>Seu e-mail</span><input id="accountEmail" type="email" inputmode="email" autocomplete="email" placeholder="voce@exemplo.com"></label><button class="btn blue drawer-submit" type="button" onclick="toast(\'Login demonstrativo\')">Continuar</button><a class="admin-link" href="admin.html">Acessar painel administrativo →</a>')};function openAdmin(){openDrawer('<h2>Painel administrativo</h2><p style="color:#66758c">Visão demonstrativa para gestão da loja.</p><div class="cart-line"><b>128</b><span>Produtos cadastrados</span></div><div class="cart-line"><b>12</b><span>Pedidos pendentes</span></div><div class="cart-line"><b>R$ 18.490</b><span>Vendas no mês</span></div><a class="btn blue drawer-submit" href="admin.html">Ver dashboard</a>')};function openWhatsApp(){openWhatsAppMessage(commerceSettings.message)};function scrollToTop(){window.scrollTo({top:0,behavior:'smooth'})}
const search=document.querySelector('#search');search.addEventListener('input',()=>{let q=search.value.toLowerCase();let s=document.querySelector('#suggestions');if(!q){s.style.display='none';search.setAttribute('aria-expanded','false');renderCatalog();return}let hits=products.filter(p=>p.n.toLowerCase().includes(q)||p.cat.toLowerCase().includes(q)).slice(0,4);s.innerHTML=hits.map(p=>`<button class="suggestion" type="button" role="option" onclick="search.value='${p.n}';search.setAttribute('aria-expanded','false');document.querySelector('#suggestions').style.display='none';renderCatalog();document.querySelector('#catalogo').scrollIntoView({behavior:'smooth'})"><b>${p.n}</b><small>${p.cat} · ${brl(p.price)}</small></button>`).join('');s.style.display=hits.length?'block':'none';search.setAttribute('aria-expanded',hits.length?'true':'false');renderCatalog()});document.querySelector('#sort').addEventListener('change',renderCatalog);document.querySelector('#cartBtn').onclick=openCart;document.querySelector('#accountBtn').onclick=openAccount;document.querySelector('#favBtn').onclick=()=>{activeCat='Todas';document.querySelector('#catalogo').scrollIntoView({behavior:'smooth'});document.querySelector('#search').value='';document.querySelector('#catalogGrid').innerHTML=(products.filter(p=>favs.includes(p.id)).map(card).join('')||'<div class="empty">Você ainda não favoritou nenhum produto.</div>')};document.querySelector('#drawer').addEventListener('click',e=>{if(e.target.id==='drawer')closeDrawer()});renderCats();initCategoryCarousel();render();
document.querySelector('#filterToggle').onclick=()=>document.querySelector('#filterPills').classList.toggle('show');
document.querySelectorAll('[data-store-whatsapp]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();openWhatsApp()}));
let cepLookupController=null,cepLookupTimer=null;
function formatCep(value){const digits=String(value||'').replace(/\D/g,'').slice(0,8);return digits.length>5?`${digits.slice(0,5)}-${digits.slice(5)}`:digits}
function setCepResult(type,title,address='',detail=''){
 const result=document.querySelector('#cepResult');if(!result)return;
 result.hidden=false;result.className=`cep-result ${type}`;
 result.querySelector('strong').textContent=title;
 result.querySelector('[data-cep-address]').textContent=address;
 result.querySelector('[data-cep-detail]').textContent=detail;
}
async function lookupCep(){
 const input=document.querySelector('#productCep'),button=document.querySelector('[data-cep-submit]');if(!input||!button)return;
 const cep=input.value.replace(/\D/g,'');input.value=formatCep(cep);
 if(!/^\d{8}$/.test(cep)){setCepResult('error','Digite um CEP válido com 8 números.');input.setAttribute('aria-invalid','true');return}
 input.removeAttribute('aria-invalid');cepLookupController?.abort();cepLookupController=new AbortController();
 button.disabled=true;button.textContent='Buscando…';setCepResult('loading','Buscando endereço…');
 try{
  const response=await fetch(`https://viacep.com.br/ws/${cep}/json/`,{signal:cepLookupController.signal});
  if(!response.ok)throw new Error('request');
  const data=await response.json();if(data.erro){setCepResult('error','CEP não encontrado.','Confira os números e tente novamente.');return}
  const street=[data.logradouro,data.complemento].filter(Boolean).join(', ');
  const city=[data.localidade,data.uf].filter(Boolean).join(' - ');
  const address=[street,data.bairro].filter(Boolean).join(' · ')||'Endereço localizado';
  setCepResult('success',`CEP ${data.cep||formatCep(cep)}`,address,city);
 }catch(error){
  if(error.name!=='AbortError')setCepResult('error','Não foi possível consultar o CEP.','Verifique sua conexão e tente novamente.');
 }finally{
  if(button){button.disabled=false;button.textContent='Calcular'}
 }
}
function setupCepLookup(){
 const input=document.querySelector('#productCep');if(!input)return;
 input.addEventListener('input',()=>{
  input.value=formatCep(input.value);input.removeAttribute('aria-invalid');clearTimeout(cepLookupTimer);
  const result=document.querySelector('#cepResult');if(input.value.replace(/\D/g,'').length<8&&result)result.hidden=true;
  if(input.value.replace(/\D/g,'').length===8)cepLookupTimer=setTimeout(lookupCep,250);
 });
 input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();clearTimeout(cepLookupTimer);lookupCep()}});
}
function openProduct(id){
 const p=products.find(x=>x.id===id);if(!p)return;
 const images=[p.img,...(p.images||[])];let i=0;
 const rating=Number.isFinite(p.rating)&&Number.isFinite(p.reviews)?`<div class="detail-rating">${'★'.repeat(Math.round(p.rating))} <span>(${p.reviews} avaliações)</span></div>`:'';
 const stockMessage=Number.isFinite(p.stock)?(p.stock>0?`${p.stock} unidade${p.stock!==1?'s':''} disponível${p.stock!==1?'eis':''}`:'Consulte a disponibilidade com a loja'):'Disponível para testar a compra';
 const draw=()=>{
  openDrawer(`<div class="product-detail-breadcrumb">Início &nbsp;/&nbsp; ${storeHtml(p.cat)} &nbsp;/&nbsp; ${storeHtml(p.n)}</div><div class="product-detail"><div class="detail-gallery"><button class="detail-main" type="button" aria-label="Ampliar foto"><img src="${storeHtml(images[i])}" alt="${storeHtml(p.n)}" width="900" height="700"></button><small>Fotografia ilustrativa. Confirme cores e medidas com a loja.</small>${images.length>1?`<div class="detail-thumbs">${images.map((src,n)=>`<button class="detail-thumb ${n===i?'active':''}" type="button" onclick="this.closest('.drawer-card').querySelector('.detail-main img').src='${storeHtml(src)}'"><img src="${storeHtml(src)}" alt="Foto ${n+1} de ${storeHtml(p.n)}" loading="lazy" width="120" height="90"></button>`).join('')}</div>`:''}</div><div class="detail-info"><div class="detail-actions">↗ Compartilhar&nbsp;&nbsp; ♡ Favoritar</div><small class="detail-badge">CATÁLOGO ATACAREJO DOS MÓVEIS</small><h2>${storeHtml(p.n)}</h2><p class="detail-code">Código: ${storeHtml(productCode(p))}</p>${rating}${p.old?`<del>${brl(p.old)}</del>`:''}<strong>${brl(p.price)}</strong><p class="detail-payment">Preço à vista · consulte condições com a loja</p><p class="detail-stock">${stockMessage}</p><div class="detail-commerce-actions">${p.whatsappEnabled!==false?`<button class="product-whatsapp detail-whatsapp" type="button" onclick="buyProductWhatsApp(${p.id})">${storeIcon('whatsapp')}<span><b>${storeHtml(commerceSettings.buttonText)}</b><small>${storeHtml(commerceSettings.buttonSubtitle)}</small></span>${storeIcon('arrow')}</button>`:''}${p.cartEnabled!==false?`<button class="product-add-bag detail-add-bag" type="button" onclick="addCart(${p.id})">${storeIcon('bag')}<span>Adicionar à sacola</span></button>`:''}</div><button class="detail-cart-link" type="button" onclick="openCart()">Ir para minha sacola&nbsp; →</button><hr><p>🚚 &nbsp;Calcule a entrega</p><div class="cep-row"><label class="sr-only" for="productCep">CEP</label><input id="productCep" type="text" inputmode="numeric" autocomplete="postal-code" pattern="[0-9-]*" maxlength="9" aria-label="CEP" aria-describedby="cepResult" placeholder="00000-000"><button class="btn" type="button" data-cep-submit onclick="lookupCep()">Calcular</button></div><div id="cepResult" class="cep-result" role="status" aria-live="polite" hidden><span class="cep-result-pin" aria-hidden="true">⌖</span><div><strong></strong><span data-cep-address></span><small data-cep-detail></small></div></div><small class="cep-helper">Digite os 8 números do CEP para localizar o endereço.</small><p class="detail-safe">♢ &nbsp;A finalização do atendimento é feita diretamente com a loja.</p></div></div><section class="detail-description"><h3>Conheça o produto</h3><p>${storeHtml(p.description||`O produto ${p.n.toLowerCase()} traz uma nova possibilidade para o seu ambiente.`)}</p></section></div>`);
  document.querySelector('#drawer').classList.add('product-detail-open');
  document.querySelector('.detail-main').onclick=()=>openLightbox(p.id,i);
  setupCepLookup();
 };
 draw();
}
function openLightbox(id,index){const p=products.find(x=>x.id===id);if(!p)return;const imgs=[p.img,...(p.images||[])];let i=index||0,touchStart=0;const returnFocus=document.activeElement;const modal=document.createElement('div');modal.className='image-lightbox';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label',`Galeria de ${p.n}`);modal.innerHTML=`<button class="lightbox-close" type="button" aria-label="Fechar">×</button><button class="lightbox-prev" type="button" aria-label="Foto anterior">‹</button><img alt="${p.n}" width="1200" height="900"><button class="lightbox-next" type="button" aria-label="Próxima foto">›</button><small>Deslize ou use as setas para navegar · ESC para fechar</small>`;document.body.append(modal);document.body.classList.add('lightbox-open');const image=modal.querySelector('img');const paint=()=>{image.src=imgs[i];modal.querySelector('.lightbox-prev').hidden=imgs.length<2;modal.querySelector('.lightbox-next').hidden=imgs.length<2};const previous=()=>{i=(i-1+imgs.length)%imgs.length;paint()};const next=()=>{i=(i+1)%imgs.length;paint()};paint();const close=()=>{modal.remove();document.body.classList.remove('lightbox-open');document.removeEventListener('keydown',key);returnFocus?.focus?.()};const key=e=>{if(e.key==='Escape')close();if(e.key==='ArrowLeft')previous();if(e.key==='ArrowRight')next()};modal.onclick=e=>{if(e.target===modal)close()};modal.addEventListener('touchstart',e=>{touchStart=e.changedTouches[0].clientX},{passive:true});modal.addEventListener('touchend',e=>{const delta=e.changedTouches[0].clientX-touchStart;if(Math.abs(delta)>50)(delta>0?previous:next)()},{passive:true});modal.querySelector('.lightbox-close').onclick=close;modal.querySelector('.lightbox-prev').onclick=previous;modal.querySelector('.lightbox-next').onclick=next;document.addEventListener('keydown',key);modal.querySelector('.lightbox-close').focus()}
document.addEventListener('click',e=>{const productCard=e.target.closest('.catalog-card,.product-card');if(productCard&&!e.target.closest('button')){const p=products.find(x=>x.id===Number(productCard.dataset.productId));if(p)openProduct(p.id)}});document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.catalog-card,.product-card')){e.preventDefault();const p=products.find(x=>x.id===Number(e.target.dataset.productId));if(p)openProduct(p.id)}});
// Responsive navigation and filters reuse the same product state.
function openNavigation(){openDrawer(`<h2>Explore a loja</h2><nav class="menu-links" aria-label="Menu móvel">${['Todas',...cats.map(c=>c[0])].map(c=>`<button type="button" onclick="closeDrawer();filterCategory('${c}')">${c==='Todas'?'Todas as categorias':c}</button>`).join('')}<button type="button" onclick="closeDrawer();showOffers()">Ofertas</button><button type="button" onclick="openAccount()">Minha conta</button><button type="button" onclick="closeDrawer();document.querySelector('#favBtn').click()">Favoritos</button><button type="button" onclick="openWhatsApp()">Atendimento</button></nav>`);document.querySelector('.menu')?.setAttribute('aria-expanded','true')}
document.querySelector('.menu').onclick=openNavigation;
document.querySelector('#filterToggle').onclick=()=>openDrawer(`<h2>Filtrar por categoria</h2><nav class="menu-links">${['Todas',...cats.map(c=>c[0])].map(c=>`<button onclick="closeDrawer();filterCategory('${c}')">${c}</button>`).join('')}</nav>`);
document.querySelector('#searchBtn').onclick=()=>{document.querySelector('#suggestions').style.display='none';search.blur();renderCatalog();document.querySelector('#catalogo').scrollIntoView({behavior:'smooth'})};
search.addEventListener('keydown',e=>{if(e.key==='Enter')document.querySelector('#searchBtn').click()});
document.addEventListener('keydown',e=>{const drawer=document.querySelector('#drawer');if(e.key==='Escape'&&drawer.classList.contains('open'))closeDrawer();if(e.key==='Tab'&&drawer.classList.contains('open')){const focusable=[...drawer.querySelectorAll('button:not([disabled]),a[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')].filter(el=>el.offsetParent!==null);if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});window.addEventListener('popstate',()=>{if(document.querySelector('#drawer').classList.contains('open'))closeDrawer(true)});
const footerInfo={
 about:{title:'Sobre nós',body:'O Atacarejo dos Móveis está em Ribeira do Pombal para ajudar você a transformar cada ambiente com variedade, atendimento próximo e condições facilitadas.'},
 store:{title:'Nossa loja',body:'Visite-nos na Praça Ricardo Borges, 75, próximo à Igreja Velha, no Centro de Ribeira do Pombal - BA. CEP 48400-000.'},
 privacy:{title:'Política de privacidade',body:'Seus dados são tratados com cuidado e utilizados somente para viabilizar o atendimento e os serviços solicitados. Para consultar informações específicas, fale com a nossa equipe.'},
 terms:{title:'Termos de uso',body:'Imagens, preços e condições deste ambiente são demonstrativos. Consulte a equipe da loja para confirmar disponibilidade, medidas, prazos e condições comerciais vigentes.'},
 help:{title:'Central de ajuda',body:'Precisa de ajuda para escolher um produto, entender uma condição ou acompanhar um atendimento? Nossa equipe está disponível pelo WhatsApp.'},
 returns:{title:'Trocas e devoluções',body:'As condições de troca e devolução podem variar conforme o produto e a compra. Fale com a nossa equipe e tenha em mãos os dados do pedido.'},
 delivery:{title:'Entrega e prazos',body:'Prazos e disponibilidade de entrega dependem do produto e do endereço. Consulte nossa equipe para receber uma previsão atualizada.'}
};
document.querySelectorAll('[data-footer-info]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();const item=footerInfo[link.dataset.footerInfo];if(item)openDrawer(`<div class="footer-info-dialog"><h2>${item.title}</h2><p>${item.body}</p><button class="btn blue" onclick="closeDrawer();openWhatsApp()">Falar com a equipe</button></div>`)}));
document.querySelector('[data-youtube-placeholder]')?.addEventListener('click',()=>toast('Canal do YouTube em breve.'));

function catalogCard(p){return officialProductCard(p)}
document.querySelector('#categoriesMenu').onclick=openNavigation;
const categoryButton=document.querySelector('#categoriesMenu'); const categoryDropdown=document.createElement('div'); categoryDropdown.className='category-dropdown'; let categoryMenuItems=[['Sala de estar','Sala'],['Quarto','Quarto'],['Cozinha e jantar','Cozinha'],['Escritório','Escritório'],['Organização','Organização'],['Eletros','Eletrodomésticos']]; function renderCategoryMenu(){categoryDropdown.replaceChildren(...categoryMenuItems.map(([label,category])=>{const button=document.createElement('button');button.type='button';button.textContent=label;button.onclick=()=>filterCategory(category);return button}))} renderCategoryMenu(); document.querySelector('.nav').after(categoryDropdown); categoryButton.onclick=(e)=>{e.stopPropagation();categoryDropdown.classList.toggle('open')}; document.addEventListener('click',e=>{if(!categoryDropdown.contains(e.target)&&e.target!==categoryButton)categoryDropdown.classList.remove('open')});

document.querySelectorAll('[data-nav-category]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();filterCategory(link.dataset.navCategory)}));
document.querySelector('[data-nav-offers]')?.addEventListener('click',event=>{event.preventDefault();showOffers()});
document.querySelector('[data-nav-home]')?.addEventListener('click',event=>{event.preventDefault();scrollToTop()});

const ambientSection=document.querySelector('.ambient-promo'); const catalogueSection=document.querySelector('#catalogo'); if(ambientSection&&catalogueSection) catalogueSection.after(ambientSection);
const benefitsSection=document.createElement('section'); benefitsSection.className='benefits reference-benefits'; benefitsSection.innerHTML='<div><b>▱</b><span>Entrega Rápida<small>para toda a região</small></span></div><div><b>✥</b><span>Móveis de Qualidade<small>com garantia</small></span></div><div><b>▣</b><span>Pagamento Facilitado<small>até 12x no cartão</small></span></div><div><b>◉</b><span>Atendimento Especializado<small>para te ajudar sempre</small></span></div>'; const catalogSection=document.querySelector('#catalogo'); if(catalogSection) catalogSection.after(benefitsSection);

